url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Sustainable Livestock Guide" # the name of your site, e.g. ACME Corp.
sass:
  sass_dir: assets/css
exclude:
  - node_modules
  - dist
  - docs
